config/routes.rb
Rails.application.routes.draw do
  devise_for :order_items
  devise_for :orders
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :weapons, only: [:index, :show] do
    member do
<<<<<<< HEAD
      post :add_to_cart, :remove_item_from_cart, :increase_cart_item_quantity, :decrease_cart_item_quantity
    end
    collection do
      post :remove_all_from_cart, :place_order
=======
      post :add_to_cart
    end
    collection do
      post :remove_from_cart
>>>>>>> c8e0775f412cce674971b314da53e2d873e3689f
    end
  end

  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/cart', to: 'pages#cart'
  get '/checkout', to: 'pages#checkout'

  root :to => "pages#home"
end

app/views/layouts/shared/_footer.html.erb
    <footer class="footer">
    </footer>
    <script>
      document.addEventListener('DOMContentLoaded', () => {

        // Get all "navbar-burger" elements
        const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

        // Check if there are any navbar burgers
        if ($navbarBurgers.length > 0) {

          // Add a click event on each of them
          $navbarBurgers.forEach( el => {
            el.addEventListener('click', () => {

              // Get the target from the "data-target" attribute
              const target = el.dataset.target;
              const $target = document.getElementById(target);

              // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
              el.classList.toggle('is-active');
              $target.classList.toggle('is-active');

            });
          });
        }

      });
    </script>
  </body>
</html>

app/views/layouts/shared/_header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Crimson Caravan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/vue"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar is-white topNav">
			<div class="container">
				<div class="navbar-brand">
					<i><%= link_to "The Crimson Caravan", root_path, :alt => "Logo", :class => "navbar-item subtitle is-4" %></i>
					<div class="navbar-burger burger" data-target="topNav">
						<span></span>
						<span></span>
						<span></span>
					</div>
				</div>
				<div id="topNav" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to "Weapons", weapons_path, :class => "navbar-item" %>
          <a class="navbar-item" href="#">Ammunition (coming soon)</a>
          <%= link_to "About", about_path, :class => "navbar-item" %>
          <%= link_to "Contact", contact_path, :class => "navbar-item" %>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <% if user_signed_in? %>
                <p class="control">
                  <span class="tag is-small is-primary is-outlined">
                      <i class="fas fa-sign-out-alt" style="padding-right: 5px;"></i>
                      <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
                  </span>
              <% else %>
                <p class="control">
                  <span class="tag is-small is-primary is-outlined">
                      <i class="fas fa-sign-in-alt" style="padding-right: 5px;"></i>
                      <%= link_to "Log in", new_user_session_path, :method => :get %>
                  </span>
                </p>
              <% end %>
              <p class="control">
                <span class="tag is-small is-primary is-outlined">
                    <i class="fas fa-shopping-cart" style="padding-right: 5px;"></i>
                    <%= link_to "Cart", cart_path, :method => :get %>
                </span>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>
<<<<<<< HEAD
=======
  Cart
  <%= debug session[:weapon_item] %>
  <%= link_to 'Clear weapons', remove_from_cart_weapons_path, method: :post %>
>>>>>>> c8e0775f412cce674971b314da53e2d873e3689f
  <% if flash[:notice].present? %>
    <div class="notification is-primary">
      <button class="delete"></button>
      <%= flash[:notice] %>
    </div>
<<<<<<< HEAD
  <% end %>
  <% if flash[:remove].present? %>
    <div class="notification is-warning">
      <button class="delete"></button>
      <%= flash[:remove] %>
    </div>
  <% end %>
  <% if flash[:update].present? %>
    <div class="notification is-warning">
      <button class="delete"></button>
      <%= flash[:update] %>
    </div>
=======
>>>>>>> c8e0775f412cce674971b314da53e2d873e3689f
  <% end %>