config/routes.rb
Rails.application.routes.draw do
  devise_for :order_items
  devise_for :orders
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :weapons, only: [:index, :show] do
    member do
<<<<<<< HEAD
      post :add_to_cart, :remove_item_from_cart, :increase_cart_item_quantity, :decrease_cart_item_quantity
    end
    collection do
      post :remove_all_from_cart, :place_order
=======
      post :add_to_cart
    end
    collection do
      post :remove_from_cart
>>>>>>> c8e0775f412cce674971b314da53e2d873e3689f
    end
  end

  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/cart', to: 'pages#cart'
  get '/checkout', to: 'pages#checkout'

  root :to => "pages#home"
end

app/views/pages/_page.html.erb
<div class="hero-body">
  <div class="container has-text-centered">
    <div class="columns is-mobile">
      <div class="column is-6 is-offset-3">
        <h1 class="title">
          <%= page.title %>
        </h1>
        <div class="tags is-centered">
        </div>
        <h2 class="subtitle is-3">
          <%= page.main_content %>
        </h2>
        <h2 class="subtitle is-3">
          <%= page.secondary_content %>
        </h2>
        <aside>
          <%= page.sidebar %>
        <aside>
      </div>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
<%= render partial: "page", locals: {page: @page} %>

app/views/pages/cart.html.erb
<div class="container">
Cart
  <%= debug session[:weapon_item] %>
  <div class="columns is-mobile">
    <div class="column"></div>
    <div class="column is-10">
      <% if (!session[:weapon_item].empty?) %>
        <table class="table">
          <thead>
            <tr>
              <th><abbr title="ID">Weapon Number</abbr></th>
              <th><abbr title="Name">Name</abbr></th>
              <th><abbr title="Quantity">Quantity</abbr></th>
              <th><abbr title="Unit Price">Unit Price</abbr></th>
              <th><abbr title="Price">Price</abbr></th>
            </tr>
          </thead>
          <tbody>
            <%# foreach %>
            <% subtotal = 0 %>
            <% session[:weapon_item].each do |s| %>
            <tr>
              <td><%= s["id"] %></td>
              <td><%= s["name"] %></td>
              <td>
                <%= s["quantity"] %>

                <%= link_to raw("<span class='button is-small is-outlined'><i class='fas fa-plus'></i></span>"), increase_cart_item_quantity_weapon_path(s["id"].to_i), method: :post %>
                <%= link_to raw("<span class='button is-small is-outlined'><i class='fas fa-minus'></i></span>"), decrease_cart_item_quantity_weapon_path(s["id"].to_i), method: :post %>
              </td>
              <td><%= number_to_currency(s["price"]) %></td>
              <td><%= number_to_currency(s["price"].to_f * s["quantity"].to_i) %></td>
              <td>
                <span class="button is-small is-outlined is-danger">
                  <%= link_to 'Remove', remove_item_from_cart_weapon_path(s["id"].to_i), method: :post %>
                </span>
              </td>
              <% subtotal = subtotal + (s["price"].to_f * s["quantity"].to_i) %>
            </tr>
            <% end %>
            <%# #end foreach %>
          </tbody>
          <tfoot>
            <tr>
              <th></th>
              <th></th>
              <th></th>
              <th><abbr title="Subtotal">Subtotal: </abbr></th>
              <th><%= number_to_currency(subtotal) %></th>
            </tr>
          </tfoot>
        </table>
        <p class="control">
          <span class="button is-small is-secondary is-outlined">
            <%= link_to 'Empty Cart', remove_all_from_cart_weapons_path, method: :post %>
          </span>
          <span class="button is-small is-primary is-outlined">
            <%= link_to 'Proceed to Checkout', checkout_path %>
          </span>
        </p>
      <% else %>
        <h3 class="title is-3">Cart is empty...</h3>
      <% end %>
    </div>
    <div class="column"></div>
  </div>
</div>

app/views/pages/checkout.html.erb
<div class="container">
Cart
  <%= debug current_user.id %>
  <div class="columns is-mobile">
    <div class="column"></div>
    <div class="column is-10">
    <% if user_signed_in? %>
      <h2 class="subtitle is-3">Here are your order details, <%= current_user.first_name %>!</h2>
      <% if (!session[:weapon_item].empty?) %>
        <table class="table">
          <thead>
            <tr>
              <th><abbr title="ID">Weapon Number</abbr></th>
              <th><abbr title="Name">Name</abbr></th>
              <th><abbr title="Quantity">Quantity</abbr></th>
              <th><abbr title="Price">Price</abbr></th>
            </tr>
          </thead>
          <tbody>
            <%# foreach %>
            <% subtotal = 0 %>
            <% session[:weapon_item].each do |s| %>
            <tr>
              <td><%= s["name"] %></td>
              <td><%= s["quantity"] %></td>
              <td><%= number_to_currency(s["price"]) %></td>
              <td><%= number_to_currency(s["price"].to_f * s["quantity"].to_i) %></td>
              <% subtotal = subtotal + (s["price"].to_f * s["quantity"].to_i) %>
            </tr>
            <% end %>
            <%# #end foreach %>
          </tbody>
          <tfoot>
            <%# Subtotal %>
            <tr>
              <th></th>
              <th></th>
              <th><abbr title="Subtotal">Subtotal: </abbr></th>
              <th><%= number_to_currency(subtotal) %></th>
            </tr>
            <%# Taxes %>
            <tr>
              <th></th>
              <th></th>
              <th><abbr title="Tax">Tax: </abbr></th>
              <% tax_rate = current_user.province.hst + current_user.province.gst + current_user.province.pst %>
              <% taxes = subtotal * (tax_rate) %>
              <th><%= number_to_currency(taxes) %></th>
            </tr>
            <%# Grand total %>
            <tr>
              <th></th>
              <th></th>
              <th><abbr title="Total">Total: </abbr></th>
              <% total = subtotal + taxes %>
              <th><%= number_to_currency(total) %></th>
            </tr>
          </tfoot>
        </table>
        <p class="control">
          <span class="button is-small is-secondary is-outlined">
            <%= link_to 'Back to Cart', cart_path %>
          </span>
          <span class="button is-small is-primary is-outlined">
            <%= link_to 'Place Order', place_order_weapons_path, method: :post %>
          </span>
        </p>
        <% end %>
      <% else %>
        <% redirect_to new_user_session_path %>
      <% end %>
    </div>
    <div class="column"></div>
  </div>
</div>

app/views/pages/contact.html.erb
<%= render partial: "page", locals: {page: @page} %>

app/views/pages/home.html.erb
  <div class="hero-body">
    <div class="container has-text-centered">
      <div class="column is-6 is-offset-3">
        <h1 class="title">
            Don't Just Survive.
        </h1>
        <div class="tags is-centered">
          <% if user_signed_in? %>
            <h2 class="subtitle is-3">Welcome back, <%= current_user.email %>!</h2>
          <% else %>
            <span class="tag is-normal is-primary" style="font-size: 0.9rem;"><i class="fas fa-user-plus" style="padding-right: 5px;"></i>
              <%= link_to "Sign up", new_user_registration_path, :method => :get %>
            </span>
            <span class="tag is-normal is-light" style="font-size: 0.9rem;"><i class="fas fa-sign-in-alt" style="padding-right: 5px;"></i>
              <%= link_to "Log in", new_user_session_path, :method => :get %>
          </span>
          <% end%>
        </div>
        <h2 class="subtitle is-3">
          <blockquote cite="https://www.brainyquote.com/quotes/noam_chomsky_447307?src=t_nuclear_war">
            "There are two problems for our species' survival - nuclear war and environmental catastrophe - and we're hurtling towards them. Knowingly."
            <p>- Noam Chomsky</p>
          </blockquote>
        </h2>
      </div>
    </div>
  </div>
</section>