config/routes.rb
Rails.application.routes.draw do
  devise_for :order_items
  devise_for :orders
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :weapons, only: [:index, :show] do
    member do
<<<<<<< HEAD
      post :add_to_cart, :remove_item_from_cart, :increase_cart_item_quantity, :decrease_cart_item_quantity
    end
    collection do
      post :remove_all_from_cart, :place_order
=======
      post :add_to_cart
    end
    collection do
      post :remove_from_cart
>>>>>>> c8e0775f412cce674971b314da53e2d873e3689f
    end
  end

  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/cart', to: 'pages#cart'
  get '/checkout', to: 'pages#checkout'

  root :to => "pages#home"
end

app/models/weapon.rb
class Weapon < ApplicationRecord
  mount_uploader :image, DefaultUploader
  paginates_per 21

  has_many :weapon_ammunitions, :dependent => :destroy
  has_many :ammunitions, through: :weapon_ammunitions
  accepts_nested_attributes_for :weapon_ammunitions, allow_destroy: true

  belongs_to :category
  belongs_to :status

  validates :name, uniqueness:true
  validates :name, :description, presence: true
  validates :weight, :price, numericality: { greater_than_or_equal_to: 0 }

end

app/controllers/weapon_controller.rb
class WeaponController < ApplicationController
  def show
    @weapon_collection = Weapon.order(:name)
  end

  def index
    @weapon = Weapon.find(params[:id])
  end
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  def index
    if params[:search].present? && params[:filter].present? && params[:status].present?
      @weapon_collection = Weapon.order(:name).page(params[:page]).where('name LIKE ? AND category_id = ? AND status_id = ?', "%#{params[:search]}%",  params[:filter], params[:status])
    elsif params[:search].present? && params[:status].present?
      @weapon_collection = Weapon.order(:name).page(params[:page]).where('name LIKE ? AND status_id = ?', "%#{params[:search]}%", params[:status])
    elsif params[:search].present? && params[:filter].present?
      @weapon_collection = Weapon.order(:name).page(params[:page]).where('name LIKE ? AND category_id = ?', "%#{params[:search]}%",  params[:filter])
    elsif params[:filter].present? && params[:status].present?
      @weapon_collection = Weapon.order(:name).page(params[:page]).where('category_id = ? AND status_id = ?', params[:filter], params[:status])
    elsif params[:search].present?
       @weapon_collection = Weapon.order(:name).page(params[:page]).where('name LIKE ?', "%#{params[:search]}%")
    elsif params[:filter].present?
      @weapon_collection = Weapon.order(:name).page(params[:page]).where("category_id = ?", params[:filter])
    elsif params[:status].present?
       @weapon_collection = Weapon.order(:name).page(params[:page]).where("status_id = ?", params[:status])
    else
      @weapon_collection = Weapon.order(:name).page(params[:page])
    end
  end

  def show
    @weapon = Weapon.find(params[:id])
  end

  def add_to_cart
    flash[:notice] = ''
    id = params[:id].to_i
<<<<<<< HEAD
    weapon = Weapon.find(id)
    quantity = params[:quantity].to_i
    price = (weapon.price).to_i * (1 - weapon.status.discount)
    product = Hash["id" => id, "name" => weapon.name, "quantity" => quantity, "price" => price]
    unless session[:weapon_item].any? { |item| item['id'] == id}
      flash[:notice] = "#{weapon.name} added to cart!"
      session[:weapon_item] << product
=======
    quantity = params[:quantity].to_i
    weapon = Hash["id" => id, "quantity" => quantity]
    unless session[:weapon_item].any? { |item| item['id'] == id}
      product = Weapon.find(1)
      flash[:notice] = "#{product.name} added to cart!"
      session[:weapon_item] << weapon
>>>>>>> c8e0775f412cce674971b314da53e2d873e3689f
    end
    redirect_to weapons_path
  end

<<<<<<< HEAD
  def increase_cart_item_quantity
    id = params[:id].to_i
    weapon = Weapon.find(id)
    item = session[:weapon_item].select { |item| item['id'] == id }
    item_index = session[:weapon_item].index(item[0])
    new_quantity = item[0]["quantity"] + 1
    session[:weapon_item][item_index]["quantity"] = new_quantity
    flash[:update] = "#{weapon.name} quantity increased to #{new_quantity}!"

    redirect_to cart_path
  end

  def decrease_cart_item_quantity
    id = params[:id].to_i
    weapon = Weapon.find(id)
    item = session[:weapon_item].select { |item| item['id'] == id }
    item_index = session[:weapon_item].index(item[0])
    new_quantity = item[0]["quantity"] - 1
    if new_quantity < 1
      session[:weapon_item].delete_at(item_index)
      flash[:update] = "#{weapon.name} quantity decreased to #{new_quantity} so it was removed!"
    else
     session[:weapon_item][item_index]["quantity"] = new_quantity
      flash[:update] = "#{weapon.name} quantity decreased to #{new_quantity}!"
    end
    redirect_to cart_path
  end

  def remove_item_from_cart
    id = params[:id].to_i
    weapon = Weapon.find(id)
    flash[:remove] = "#{weapon.name} removed from cart!"
    session[:weapon_item].delete_if { |item| item['id'] == id}

    redirect_to cart_path
  end

  def remove_all_from_cart
=======
  def remove_from_cart
>>>>>>> c8e0775f412cce674971b314da53e2d873e3689f
    # session[:weapon_item].delete(params[:id])
    session[:weapon_item] = []

    redirect_to weapons_path
  end

<<<<<<< HEAD
  def place_order
    subtotal = 0
    tax_rate = current_user.province.hst + current_user.province.gst + current_user.province.pst
    session[:weapon_item].each do |w|
      subtotal = subtotal + (w["price"].to_f * w["quantity"].to_i)
    end

    taxes = subtotal * (tax_rate)
    total = subtotal + taxes

    order = Order.create(user_id: current_user.id, order_status: "pending", subtotal: subtotal, taxes: taxes, total: total)

    session[:weapon_item].each do |w|
      order_item = OrderItem.create(weapon_id: w['id'].to_i, order_id: order.id, quantity: w['quantity'].to_i)
    end

    session[:weapon_item] = []
    redirect_to root_path
  end

=======
>>>>>>> c8e0775f412cce674971b314da53e2d873e3689f
  private
    def weapon_params
      params.require(:search, :filter, :status).permit(:search, :filter, :status)
    end
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/weapons/index.html.erb
<div class="section">
  <div>
    <%= form_tag(weapons_path, method: "get", :class => "box") do %>
      <div class="field has-addons">
        <div class="control is-expanded">
          <%= text_field_tag(:search, '', class: "input has-text-centered", placeholder: "» find me «") %>
        </div>
      </div>
      <div class="field has-addons">
        <div class="control is-expanded">
          <div class="select">
            <%= select_tag 'status', options_from_collection_for_select(Status.all, :id, :name), include_blank: 'Status Filter'  %>
          </div>
          <div class="select">
            <%= select_tag 'filter', options_from_collection_for_select(Category.all, :id, :name), include_blank: 'Category Filter'  %>
          </div>
        </div>
      </div>
      <div class="control">
        <%= button_tag 'Search', {:controller => "weapons", :action => "index", :methdod => :post, class: "button is-info" , params: {search: :search, filter: :filter}} %>
        <%= button_tag 'Clear', {:controller => "weapons", :action => "index", :methdod => :post, class: "button is-info" , params: {search: '', filter: ''}} %>
      </div>
    <% end %>
  </div>

  <!-- Weapons -->
  <div class="columns is-mobile">
  <div class="column">
    <% @weapon_collection.in_groups_of(3, false) do |group| %>
      <div class="column">
        <% group.each do |weapon| %>
          <div class="column is-one-third">
            <div class="card large">

              <div class="card-image">
                <figure class="image">
                  <%= link_to(image_tag(weapon.image.medium.url, alt: "#{weapon.name}"), weapon_path(weapon)) if weapon.image? %>
                </figure>
              </div><!-- /card-image -->

              <div class="card-content">
                <div class="content">
                  <div class="content">
                    <p class="title is-4 no-padding">
                      <%= link_to weapon.name, weapon_path(weapon) %>
                    </p>
                    <span class="title is-6">
                      <% if weapon.status.name == 'new' %>
                        <span class="subtitle is-6">C$ <%= '%.2f' % (weapon.price * ( 1 - weapon.status.discount )) %></span>
                        <span class= "tag is-success"><%= weapon.status.name %></span>
                        <p class="discount"><span class="subtitle is-6">C$ <%= '%.2f' % (weapon.price) %></span></p>
                      <% elsif weapon.status.name == 'on sale' %>
                        <span class="subtitle is-6">C$ <%= '%.2f' % (weapon.price * ( 1 - weapon.status.discount )) %></span>
                        <span class= "tag is-info"><%= weapon.status.name %></span>
                        <p class="discount"><span class="subtitle is-6">C$ <%= '%.2f' % (weapon.price) %></span></p>
                      <% else %>
                        <span class="subtitle is-6">C$ <%= '%.2f' % (weapon.price * ( 1 - weapon.status.discount )) %></span>
                      <% end %>
                    </span>
                  </div>
                </div>
              </div><!-- /card-content -->

            </div><!-- /card -->
          </div><!-- /column -->
        <% end %>
      </div><!-- /row column -->
    <% end %>
  </div>
  </div>
  <%= paginate @weapon_collection %>
</div>

app/views/weapons/show.html.erb

<div class="columns">
  <div class="column previous-weapon"></div>
  <div class="column is-6">
    <div class="card large">
      <div class="card-image">
        <figure class="image">
          <%= image_tag(@weapon.image.url, alt: "#{@weapon.name}") if @weapon.image? %>
        </figure>
      </div><!-- /card-image -->

      <div class="card-content">
        <div class="content">
          <div class="content">
            <p class="title is-4 no-padding">
              <%= @weapon.name %>
            </p>
            <span class="title is-6">
                <% if @weapon.status.name == 'new' %>
                  <span class="subtitle is-6">C$ <%= '%.2f' % (@weapon.price * ( 1 - @weapon.status.discount )) %></span>
                  <span class= "tag is-success"><%= @weapon.status.name %></span>
                  <p class="discount"><span class="subtitle is-6">C$ <%= '%.2f' % (@weapon.price) %></span></p>
                <% elsif @weapon.status.name == 'on sale' %>
                  <span class="subtitle is-6">C$ <%= '%.2f' % (@weapon.price * ( 1 - @weapon.status.discount )) %></span>
                  <span class= "tag is-info"><%= @weapon.status.name %></span>
                  <p class="discount"><span class="subtitle is-6">C$ <%= '%.2f' % (@weapon.price) %></span></p>
                <% else %>
                  <span class="subtitle is-6">C$ <%= '%.2f' % (@weapon.price * ( 1 - @weapon.status.discount )) %></span>
                <% end %>
            </span>
          </div>
          <span class="subtitle is-5"> Ammunition:</span>
            <% @weapon.ammunitions.each do |ammo| %>
              <!-- change link_to ammo -->
              <span class="tag is-light"><%= ammo.name %></span>
            <% end %>
          <p class="box">
            <%= @weapon.description %>
          </p>
          <nav class="level is-mobile">
            <div class="navbar-item">
<<<<<<< HEAD
=======

>>>>>>> c8e0775f412cce674971b314da53e2d873e3689f
              <%= form_tag add_to_cart_weapon_path, method: "post" do %>
              <div class="field is-grouped">
                <p class="control">
                  <%= submit_tag("Add to cart", :class => "is-primary") %>
                  <%= select_tag "quantity", options_for_select((1..30)) %>
                </p>
              </div>
              <% end %>
<<<<<<< HEAD
            </div>
            <p id="wish" class="control">
              <input v-model="id" type="hidden" value='<%= "#{@weapon.id}" %>'>
              <input v-model="name" type="hidden" value='<%= "#{@weapon.name}" %>'>
              <button @click="persist" class="tag is-large is-outlined">
                <i class="fas fa-star" style="padding-right: 5px;"></i>
              </button>
            </p>
          </nav>

=======

            </div>
          </nav>
>>>>>>> c8e0775f412cce674971b314da53e2d873e3689f
          <nav class="level is-mobile">
            <div class="field">
              <p class="control">
                <span class="icon">
                  <%= link_to content_tag(:i, 'Back', :class => "fas fa-step-backward tag is-small is-light is-outlined"), :back %>
                </span>
              </p>
            </div>
          </nav>
        </div>
      </div><!--  /card-content -->
    </div><!-- /card -->
  </div>
  <div class="column next-weapon"></div>
</div>